internetarchive/openlibrary-bots

NY-Times-Bestseller-Bot/README.md
NY-Times-Bestseller-Bot/nyt_bestsellers_bot.py
NY-Times-Bestseller-Bot/requirements.txt

* Added Installation Instructions
* Added a requirements.txt file 
* Added Python2+3 Compatible code
References #1

Added New York Times Best Seller Bot

---

CONTRIBUTING.md
LICENSE
PULL_REQUEST_TEMPLATE.md
README.md

Closes #2 
* Added README, LICENSE, CONTRIBUTING and Pull Request Template

Added Documentation Files for the Bot Repository

---

ia-wishlist-bot/adding_wishlist_ol.py
ia-wishlist-bot/requirements.txt

Closes #11 
1. Finalised the IA Wishlist Bot

IA wishlist - Adding first 1000 books

---

google-books-bot/README.md
google-books-bot/google_books_search.py
google-books-bot/requirements.txt

This one is pretty self-documenting given the #fresh README. Let me know if you have any questions, especially as this is my first time here!

Added Google Books Search -> Open Library upload script

---

NY-Times-Bestseller-Bot/nyt_bestsellers_bot.py
old-onix-bot/onix-import.py
old-onix-bot/parse.py
old-onix-bot/urlcache.py
old-onix-bot/xmltramp.py

One syntax error remains:
```
./old-onix-bot/thread_utils.py:41:22: E999 SyntaxError: invalid syntax
raise self.exc_type, self.exc_value, self.exc_traceback
^
1     E999 SyntaxError: invalid syntax
1
```

Fix some Python 3 incompatibilities

---

README.md
onix-bot/README.md
onix-bot/onixparser.py

1. Added Inline Documentation to ONIX Bot
2. Added more documentation to the README of the individual bots.*

Added documentation to ONIX Bot

---

.github/workflows/lint_python.yml
NY-Times-Bestseller-Bot/nyt_bestsellers_bot.py
old-onix-bot/thread_utils.py
old-onix-bot/xmltramp.py

See results at https://github.com/cclauss/openlibrary-bots/actions

GitHub Action to lint Python code

---

ia-bulkmarc-bot/bulk-import.py

Improve error handling and logging of bulkmarc bot

---

.github/workflows/lint_python.yml
requirements.txt

pytest --doctest-modules . || true

---

.gitignore
twitter-borrowbot/requirements.txt
twitter-borrowbot/setup.py
twitter-borrowbot/twitterbot.py

Twitter bot 

---

.github/workflows/lint_python.yml
BWBImportBot/README.md
README.md
ia-bulkmarc-bot/bulk-import.py
ia-wishlist-bot/README.md
ia-wishlist-bot/add_works_via_wishlist.py
isbnbot/README.md

https://github.com/codespell-project/codespell/blob/master/README.rst
*

Fix typos discovered by codespell

---

.gitignore
twitter-borrowbot/services.py
twitter-borrowbot/test_borrowbot.py
twitter-borrowbot/twitterbot.py
twitter-borrowbot/twitterbotErrors.py

- Implemented try/except blocks for each method so that custom exceptions can be raised in case of a runtime exception.
- Custom exceptions are used so that the logging is cleaner and easier to expand.
- Refactored our logging system to use python's robust library logging instead of our homemade logger. Currently the logger supports 3 priorities:
1. critical --> an error that requires the main function reply_to_mentions to exit and therefore sleep for some time.
2. warning --> an error that does not require reply_to_mentions to exit but does require either an ISBN process to be skipped or worse, an entire mention to be skipped.
3. info --> logs the incoming mention & our reply.
Recommended changes made:
1.  Removed wildcard imports. …

👍 Exception Handling and logging (with recommended changes).

---

BWBCoverBot/main.py
BWBCoverBot/requirements.txt

BWB shares a bunch of zip files every month. The structure is that they share a bunch of zip files, which contain thousands of covers. The files inside the zip follow the following file names, `<isbn_10>.png`. 
The bot goes through all the files, and update the work using that corresponding data.

New bot: BWBCoverBot

---

twitter-borrowbot/requirements.txt
whitespace_work_title_cleanup_bot/README.md
whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py

* Added a remix of making_a_bot.py but for works

Add surrounding whitespace work title cleanup bot

---

whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py

black whitespace_work_title_cleanup.py

---

whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py

Clean up code formatting done in #244

re-black whitespace_work_title_cleanup.py

---

promise-bot/README.md
promise-bot/config/bot.ini
promise-bot/fix_promise_items.py
promise-bot/requirements.txt

Creates bot for fixing incorrectly imported BWB promise items.

Create bot for fixing overloaded import records

---

.github/workflows/lint_python.yml
pyproject.toml

* https://github.com/codespell-project/codespell#using-a-config-file
* https://github.com/codespell-project/codespell#pre-commit-hook

pre-commit: Put codespell config in pyproject.toml

---

BWBImportBot/parse-biblio.py
NY-Times-Bestseller-Bot/nyt_bestsellers_bot.py
coverbot/cover_updater.py
ia-bulkmarc-bot/bulk-import.py
ia-sync-bot/update-ocaid.py
ia-wishlist-bot/add_wishlist_works.py
ia-wishlist-bot/get_wishlist_works_via_isbn.py
old-onix-bot/onix-import.py
old-onix-bot/onix.py
old-onix-bot/sax_utils.py
old-onix-bot/urlcache.py
old-onix-bot/xmltramp.py
twitter-borrowbot/disabled_test_borrowbot.py
twitter-borrowbot/services.py
twitter-borrowbot/twitterbot.py

https://pypi.org/project/flynt

More Python f-strings using flynt

---

.pre-commit-config.yaml
BWBCoverBot/requirements.txt
NY-Times-Bestseller-Bot/nyt_bestsellers_bot.py
old-onix-bot/urlcache.py
old-onix-bot/xmltramp.py

Dependabot/pip/streaming form data 1.12.0

---

BWBCoverBot/tests/test_main.py

Previously the tests would fail if an SQLModel's attributes returned in a different order. E.g.:
```
- [(EditionCoverData(isbn_13='444', cover_exists=True),)]
+ [(EditionCoverData(cover_exists=True, isbn_13='444'),)]
```
Before comparison, the `EditionCoverData` models, from `SQLModel`, are now represented as dictionaries so the order doesn't matter.
Additionally, the call to the deprecated `session.execute()` was replaced with a call to `session.exec()`, and the tests were updated to reflect model objects being returned directly, rather than being nested in tuples.

Fix: BWBCoverBot's tests no longer depend on the model's attribute order
